In [25]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [26]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [27]:
## PreProcessing the data

data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis = 1)

In [28]:
## Encode the Gender to 0s and 1s

label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [29]:
## One hot encoding the Geography class

onehot_encoder_geo = OneHotEncoder(handle_unknown = 'ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [30]:
## Now doing the concetenation

data = pd.concat([data.drop('Geography', axis = 1), geo_encoded_df], axis = 1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [31]:
## Split the data into independent features and dependent features

X = data.drop('EstimatedSalary', axis = 1)
y = data['EstimatedSalary']

In [32]:
## Split the data into testing and training sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
## Scale these features

scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [34]:
## Save the encoders and scalars

with open('onehot_encoder_geo.pkl', 'rb') as file:
  label_encoder_geo=pickle.load(file)

with open('label_encoder_gender.pkl', 'rb') as file:
  label_encoder_gender=pickle.load(file)

with open('scaler.pkl', 'rb') as file:
  scaler=pickle.load(file)

#### ANN with regression problem statement

In [35]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [36]:
## Build our ANN model

model=Sequential([
  Input(shape=(X_train.shape[1],)), ## Input layer
  Dense(64, activation='relu'), ## HL1 connected with the input layer
  Dense(32, activation='relu'), ## HL2
  Dense(1) ## Output layer, no activation funcition as it must use default linear activation funciton for the regression
])

In [37]:
## Compiling the model

model.compile(optimizer='adam', loss = 'mean_absolute_error', metrics=['mae'])

In [38]:
## Summary of the model

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [39]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

## Setup tensorboard

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callbacks = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [40]:
## Setup Early Stopping

early_stopping_callback=EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [41]:
## Train the actual model

history=model.fit(
  X_train, y_train, validation_data=(X_test, y_test ), epochs=100,
  callbacks=[early_stopping_callback, tensorboard_callbacks]
)

Epoch 1/100

I0000 00:00:1784032932.127173    3507 dot_merger.cc:481] Merging Dots in computation: a_inference_one_step_on_data_232180__.8

250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 100378.3438 - mae: 100378.3438 - val_loss: 98518.6094 - val_mae: 98518.6094
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99620.8281 - mae: 99620.8281 - val_loss: 96970.6953 - val_mae: 96970.6953
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 96898.8125 - mae: 96898.8125 - val_loss: 92957.2188 - val_mae: 92957.2188
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91539.3828 - mae: 91539.3828 - val_loss: 86313.6016 - val_mae: 86313.6016
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 83785.7656 - mae: 83785.7656 - val_loss: 77784.6328 - val_mae: 77784.6328
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 74802.6562 - mae: 74802.6562 - val_loss: 69096.7656 - val_mae: 69096.7656
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 66177.1172 - mae: 66177.1172 - val_loss: 61685.0703 - val_mae: 61685.0703
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 59366.6016 - mae: 59366.6016 - val_loss: 56386.2031 - val_mae: 56386.2031
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 55019.9922 - mae: 55019.9922 - val_loss: 53461.0859 - val_mae: 53461.0859
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52573.6250 - mae: 52573.6250 - val_loss: 52070.4141 - val_mae: 52070.4141
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51378.4648 - mae: 51378.4648 - val_loss: 51478.8945 - val_mae: 51478.8945
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50878.4570 - mae: 50878.4570 - val_loss: 51225.2617 - val_mae: 51225.2617
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50637.9141 - mae: 50637.9141 - val_loss: 51082.0547 - val_mae: 51082.0547
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50499.0391 - mae: 50499.0391 - val_loss: 50979.2031 - val_mae: 50979.2031
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50398.7188 - mae: 50398.7188 - val_loss: 50908.7695 - val_mae: 50908.7695
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50316.2617 - mae: 50316.2617 - val_loss: 50837.0859 - val_mae: 50837.0859
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50256.8789 - mae: 50256.8789 - val_loss: 50778.5781 - val_mae: 50778.5781
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50196.2812 - mae: 50196.2812 - val_loss: 50727.0781 - val_mae: 50727.0781
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50140.2109 - mae: 50140.2109 - val_loss: 50686.9805 - val_mae: 50686.9805
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50098.3672 - mae: 50098.3672 - val_loss: 50648.5391 - val_mae: 50648.5391
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50054.4961 - mae: 50054.4961 - val_loss: 50612.0781 - val_mae: 50612.0781
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50011.4766 - mae: 50011.4766 - val_loss: 50576.3633 - val_mae: 50576.3633
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49975.4414 - mae: 49975.4414 - val_loss: 50544.4531 - val_mae: 50544.4531
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49942.6367 - mae: 49942.6367 - val_loss: 50517.1953 - val_mae: 50517.1953
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49909.9375 - mae: 49909.9375 - val_loss: 50488.0859 - val_mae: 50488.0859
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49883.0391 - mae: 49883.0391 - val_loss: 50469.9727 - val_mae: 50469.9727
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49851.5859 - mae: 49851.5859 - val_loss: 50447.9336 - val_mae: 50447.9336
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49830.1172 - mae: 49830.1172 - val_loss: 50414.1562 - val_mae: 50414.1562
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49807.0234 - mae: 49807.0234 - val_loss: 50399.9023 - val_mae: 50399.9023
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49786.9102 - mae: 49786.9102 - val_loss: 50378.5156 - val_mae: 50378.5156
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49767.4883 - mae: 49767.4883 - val_loss: 50363.1602 - val_mae: 50363.1602
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49747.7695 - mae: 49747.7695 - val_loss: 50353.9766 - val_mae: 50353.9766
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49732.8047 - mae: 49732.8047 - val_loss: 50341.8750 - val_mae: 50341.8750
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49716.0312 - mae: 49716.0312 - val_loss: 50333.9102 - val_mae: 50333.9102
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49701.0273 - mae: 49701.0273 - val_loss: 50327.5273 - val_mae: 50327.5273
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49687.6602 - mae: 49687.6602 - val_loss: 50318.4727 - val_mae: 50318.4727
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49671.7656 - mae: 49671.7656 - val_loss: 50320.9609 - val_mae: 50320.9609
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49657.8750 - mae: 49657.8750 - val_loss: 50308.8320 - val_mae: 50308.8320
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49646.3711 - mae: 49646.3711 - val_loss: 50303.1133 - val_mae: 50303.1133
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49630.7773 - mae: 49630.7773 - val_loss: 50299.9883 - val_mae: 50299.9883
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49623.1211 - mae: 49623.1211 - val_loss: 50290.9375 - val_mae: 50290.9375
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49611.5352 - mae: 49611.5352 - val_loss: 50295.9141 - val_mae: 50295.9141
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49600.9375 - mae: 49600.9375 - val_loss: 50295.5195 - val_mae: 50295.5195
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49591.5156 - mae: 49591.5156 - val_loss: 50288.9219 - val_mae: 50288.9219
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49581.3320 - mae: 49581.3320 - val_loss: 50285.3633 - val_mae: 50285.3633
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49571.8320 - mae: 49571.8320 - val_loss: 50290.4805 - val_mae: 50290.4805
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49567.0352 - mae: 49567.0352 - val_loss: 50280.9844 - val_mae: 50280.9844
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49555.3008 - mae: 49555.3008 - val_loss: 50272.9727 - val_mae: 50272.9727
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49549.7891 - mae: 49549.7891 - val_loss: 50277.9141 - val_mae: 50277.9141
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49540.8750 - mae: 49540.8750 - val_loss: 50267.8047 - val_mae: 50267.8047
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49534.8555 - mae: 49534.8555 - val_loss: 50273.5977 - val_mae: 50273.5977
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49529.5977 - mae: 49529.5977 - val_loss: 50264.5703 - val_mae: 50264.5703
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49521.6445 - mae: 49521.6445 - val_loss: 50262.2188 - val_mae: 50262.2188
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49515.2852 - mae: 49515.2852 - val_loss: 50259.8555 - val_mae: 50259.8555
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49506.9609 - mae: 49506.9609 - val_loss: 50267.0156 - val_mae: 50267.0156
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49501.0234 - mae: 49501.0234 - val_loss: 50267.9883 - val_mae: 50267.9883
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49496.8594 - mae: 49496.8594 - val_loss: 50256.8164 - val_mae: 50256.8164
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49490.4258 - mae: 49490.4258 - val_loss: 50251.3203 - val_mae: 50251.3203
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49484.9922 - mae: 49484.9922 - val_loss: 50254.4531 - val_mae: 50254.4531
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49476.7344 - mae: 49476.7344 - val_loss: 50257.3828 - val_mae: 50257.3828
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49473.8398 - mae: 49473.8398 - val_loss: 50251.7734 - val_mae: 50251.7734
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49468.8828 - mae: 49468.8828 - val_loss: 50250.8281 - val_mae: 50250.8281
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49462.8477 - mae: 49462.8477 - val_loss: 50259.5508 - val_mae: 50259.5508
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49455.7852 - mae: 49455.7852 - val_loss: 50261.7227 - val_mae: 50261.7227
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49453.9609 - mae: 49453.9609 - val_loss: 50258.0742 - val_mae: 50258.0742
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49446.5078 - mae: 49446.5078 - val_loss: 50261.4062 - val_mae: 50261.4062
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49443.6680 - mae: 49443.6680 - val_loss: 50253.9883 - val_mae: 50253.9883
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49437.7812 - mae: 49437.7812 - val_loss: 50262.8164 - val_mae: 50262.8164
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49433.1445 - mae: 49433.1445 - val_loss: 50265.6562 - val_mae: 50265.6562
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49433.2656 - mae: 49433.2656 - val_loss: 50262.5195 - val_mae: 50262.5195
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49424.8750 - mae: 49424.8750 - val_loss: 50261.2930 - val_mae: 50261.2930
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49418.4805 - mae: 49418.4805 - val_loss: 50262.0000 - val_mae: 50262.0000

In [42]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [43]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 14833), started 0:02:18 ago. (Use '!kill 14833' to kill it.)

In [44]:
## Evaluate model on the test data

test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50250.8281 - mae: 50250.8281
Test MAE : 50250.828125

In [45]:

model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.